"""The smaller generated CI fixture with production-like structure (docs/testing/acceptance.md#where-it-runs).

Static assets come from Scene.PRODUCTION_LIKE (assets/); this module generates the
layout layer around them:

    /World               kind assembly
        Ground           referenced mesh, outside any payload
        Crate_Unique     crate referenced directly: not instanced, not a payload
        Site_0/Area_0/Bay_0/Level_0/.../Crate_0
                         deep organizational hierarchy of kind group; each crate is a
                         payload, instanceable, and a component, and contains four
                         instanceable subcomponent bolts (nested instancing)

`expected_inventory` derives what each payload policy must compose from the
generator's parameters; tests check it against USD. The output is
deterministic: the same parameters give byte-identical files.
"""

from __future__ import annotations

import hashlib
import math
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from pxr import Gf, Sdf, Usd, Vt

from .scenes import Scene, copy_scene

if TYPE_CHECKING:
    from pathlib import Path

ORG_LEVELS = ("Site", "Area", "Bay", "Row", "Shelf")  # prim names for each organizational level

# Asset structure, copied by hand from the files in Scene.PRODUCTION_LIKE's assets/.
# Deliberately not read from the assets, so the inventory test fails if an asset changes.
CRATE_MESHES, CRATE_MATERIALS, CRATE_SUBSETS, BOLTS_PER_CRATE = 2, 2, 2, 4
BOLT_MESHES, BOLT_MATERIALS = 2, 2
ASSET_DEPTH = 3  # Looks/<Material>/Surface below an asset's root prim


@dataclass(frozen=True)
class Params:
    fanout: tuple[int, ...] = (2, 2, 3)  # children per organizational level: 2 sites x 2 areas x 3 bays
    levels: int = 3  # single-child Level_<n> Xforms below each bay, for depth
    crates_per_bay: int = 2

    def __post_init__(self) -> None:
        # expected_inventory assumes at least one instanced crate and no negative depth.
        if len(self.fanout) > len(ORG_LEVELS):
            raise ValueError(f"at most {len(ORG_LEVELS)} organizational levels")
        if any(count < 1 for count in self.fanout) or self.crates_per_bay < 1 or self.levels < 0:
            raise ValueError(f"fanout entries and crates_per_bay must be >= 1 and levels >= 0: {self}")


DEFAULT = Params()


def generate(dest: Path, params: Params = DEFAULT) -> Path:
    """Write the fixture into dest (assets/ plus layout.usda) and return the root layer path."""
    copy_scene(Scene.PRODUCTION_LIKE, dest)
    root = dest / "layout.usda"
    layer = Sdf.Layer.CreateNew(str(root))
    with Sdf.ChangeBlock():
        layer.documentation = f"Generated by tests/fixtures/production_like.py with {params}"
        layer.defaultPrim = "World"
        layer.pseudoRoot.SetInfo("metersPerUnit", 1.0)
        layer.pseudoRoot.SetInfo("upAxis", "Z")
        _xform(layer, "/World").kind = "assembly"
        # Typeless, so the referenced Mesh type is not overridden.
        ground = Sdf.PrimSpec(layer.GetPrimAtPath("/World"), "Ground", Sdf.SpecifierDef)
        ground.referenceList.Prepend(Sdf.Reference("./assets/ground.usda"))
        unique = _xform(layer, "/World/Crate_Unique")
        unique.referenceList.Prepend(Sdf.Reference("./assets/crate.usda"))
        _translate(unique, (-10, -10, 0))
        for index, bay in enumerate(_bays(params)):
            parent = bay
            for level in range(params.levels):
                parent = f"{parent}/Level_{level}"
            # Every prim between /World and the crates is a group, keeping the model hierarchy valid.
            for path in Sdf.Path(parent).GetPrefixes()[1:]:
                _xform(layer, str(path)).kind = "group"
            for n in range(params.crates_per_bay):
                crate = _xform(layer, f"{parent}/Crate_{n}")
                crate.payloadList.Prepend(Sdf.Payload("./assets/crate.usda"))
                crate.instanceable = True
                _translate(crate, (3 * index, 3 * n, 0))
    layer.Save()
    return root


def _bays(params: Params) -> list[str]:
    """Paths of the deepest organizational prims, in a fixed order."""
    paths = ["/World"]
    for level, count in enumerate(params.fanout):
        paths = [f"{p}/{ORG_LEVELS[level]}_{i}" for p in paths for i in range(count)]
    return paths


def _xform(layer: Sdf.Layer, path: str) -> Sdf.PrimSpec:
    """Define an Xform at path; ancestors not defined yet become Xforms too."""
    spec = layer.GetPrimAtPath(path)
    if spec is None:
        parent = Sdf.Path(path).GetParentPath()
        if parent != Sdf.Path.absoluteRootPath and layer.GetPrimAtPath(parent) is None:
            _xform(layer, str(parent))
        spec = Sdf.CreatePrimInLayer(layer, path)
        spec.specifier = Sdf.SpecifierDef
        spec.typeName = "Xform"
    return spec


def _translate(spec: Sdf.PrimSpec, xyz: tuple[float, float, float]) -> None:
    Sdf.AttributeSpec(spec, "xformOp:translate", Sdf.ValueTypeNames.Double3).default = Gf.Vec3d(*xyz)
    order = Sdf.AttributeSpec(spec, "xformOpOrder", Sdf.ValueTypeNames.TokenArray, variability=Sdf.VariabilityUniform)
    order.default = Vt.TokenArray(["xformOp:translate"])


def expected_inventory(params: Params, load_all: bool) -> dict[str, Any]:
    """What a stage over the fixture must compose, derived from the parameters and asset structure."""
    instanced_crates = math.prod(params.fanout) * params.crates_per_bay
    crates_composed = (instanced_crates if load_all else 0) + 1  # + Crate_Unique, never a payload
    per_crate_meshes = CRATE_MESHES + BOLTS_PER_CRATE * BOLT_MESHES
    per_crate_materials = CRATE_MATERIALS + BOLTS_PER_CRATE * BOLT_MATERIALS
    # Bolt instances: four in Crate_Unique, plus four inside the crate prototype when crates are loaded.
    prototypes = {"bolt": BOLTS_PER_CRATE * (2 if load_all else 1)}
    if load_all:
        prototypes["crate"] = instanced_crates
    level_depth = 1 + len(params.fanout) + params.levels  # /World/<org levels>/<Level_n>
    # Deepest loaded prim: a bolt's shader inside an instanced crate (+ Crate_n/Bolt_n) when
    # payloads load; otherwise the deepest Level_n (unloaded crates are not traversed), or a
    # bolt's shader in Crate_Unique (World/Crate_Unique/Bolt_n) if that is deeper.
    deepest = level_depth + 2 + ASSET_DEPTH if load_all else max(level_depth, 3 + ASSET_DEPTH)
    bays = math.prod(params.fanout)
    org_prims = sum(math.prod(params.fanout[: n + 1]) for n in range(len(params.fanout))) + bays * params.levels
    return {
        "prototypes": prototypes,  # asset name -> number of instances of its prototype
        "meshes": crates_composed * per_crate_meshes + 1,  # + Ground
        "materials": crates_composed * per_crate_materials,
        "geom_subsets": crates_composed * CRATE_SUBSETS,
        "groups": 1 + org_prims,  # /World (an assembly is a group) + every organizational prim
        # Loaded crates; an unloaded crate's kind comes from its payload, so it has none.
        "components": crates_composed,
        "deepest": deepest,
    }


def inventory(stage: Usd.Stage) -> dict[str, Any]:
    """The same counts as expected_inventory, measured by traversing the loaded composed stage.

    Prototypes are named by the assetInfo of their first instance; prototype
    prims themselves do not carry the asset's metadata. Groups and components
    count prims in a valid model hierarchy (IsGroup/IsComponent), not just
    authored kinds.
    """
    counts = {"Mesh": 0, "Material": 0, "GeomSubset": 0}
    groups = components = deepest = 0
    for prim in stage.Traverse(Usd.TraverseInstanceProxies()):
        if (type_name := str(prim.GetTypeName())) in counts:
            counts[type_name] += 1
        groups += prim.IsGroup()
        components += prim.IsComponent()
        deepest = max(deepest, prim.GetPath().pathElementCount)
    prototypes: dict[str, int] = {}
    for prototype in stage.GetPrototypes():
        name = prototype.GetInstances()[0].GetAssetInfoByKey("name")
        if name in prototypes:
            raise AssertionError(f"more than one prototype for asset {name!r}")
        prototypes[name] = len(prototype.GetInstances())
    return {
        "prototypes": prototypes,
        "meshes": counts["Mesh"],
        "materials": counts["Material"],
        "geom_subsets": counts["GeomSubset"],
        "groups": groups,
        "components": components,
        "deepest": deepest,
    }


def checksum(dest: Path) -> str:
    """SHA-256 over every file under dest: its relative path, size, and bytes, in sorted order."""
    digest = hashlib.sha256()
    for path in sorted(p for p in dest.rglob("*") if p.is_file()):
        data = path.read_bytes()
        # Length-prefixed, so a path and the contents that follow it cannot run together.
        digest.update(f"{path.relative_to(dest).as_posix()}\0{len(data)}\0".encode())
        digest.update(data)
    return digest.hexdigest()
