"""Registry of the named contract fixtures (docs/testing/strategy.md#named-contract-fixtures).

Each fixture has a stable ID, the milestones whose Tests section names it, and
an optional generator. A fixture without a generator is a stub: its owning
milestone adds the generator. tests/bpy_free/test_fixture_registry.py keeps the
IDs and milestones in sync with the docs.

Fixture cases (operation, expected outcome, requirement IDs, and qualification
phase, per docs/testing/acceptance.md#bespoke-fixtures) are not declared here
yet: M3 designs their schema with its first fixtures. Other fixtures join the
registry when a milestone assigns them in docs/testing/requirements.yaml.
"""

from __future__ import annotations

from collections.abc import Callable
from contextlib import AbstractContextManager
from dataclasses import dataclass
from pathlib import Path

from . import source_access

# A generator writes the fixture into a fresh directory and yields a handle to it.
# It is a context manager so in-process state (open stages, cache entries) is released on exit.
Generator = Callable[[Path], AbstractContextManager[object]]


@dataclass(frozen=True)
class Fixture:
    id: str
    title: str
    milestones: tuple[str, ...]  # milestones whose Tests section names this fixture
    build: Generator | None = None  # None: a stub, generated by its owning milestone


FIXTURES: dict[str, Fixture] = {
    f.id: f
    for f in (
        Fixture(
            "F-DIRTY-LAYER",
            "Dirty-layer conflict: disk changes and unsaved in-process changes coexist",
            ("M3",),
            source_access.dirty_layer,
        ),
        Fixture(
            "F-PRIVATE-STAGE",
            "Private-stage fidelity: caller stage settings differ from defaults",
            ("M3",),
            source_access.private_stage,
        ),
        Fixture(
            "F-CACHED-STAGE",
            "Cached-stage isolation: ambient stage reuse does not cross-contaminate bindings",
            ("M3",),
            source_access.cached_stage,
        ),
        Fixture("F-FAILED-SETTINGS", "Failed settings transition", ("M5",)),
        Fixture("F-SHARED-MATERIAL-FAILURE", "Shared-material failure", ("M9",)),
        Fixture("F-PUBLICATION-FAILURE", "Publication failure", ("M5",)),
        Fixture("F-PREPARATION-CLEANUP-FAILURE", "Preparation and disposal both fail", ("M5",)),
        Fixture("F-RETIREMENT-FAILURE", "Retirement failure", ("M5",)),
        Fixture("F-OWNERSHIP-AMBIGUITY", "Ownership ambiguity", ("M3", "M11")),
        Fixture("F-UNMANAGED-USER", "Unmanaged user of managed data", ("M7",)),
        Fixture("F-DETACH-SHARED", "Detach with shared instance content", ("M11",)),
        Fixture("F-DETACH-AS-IS", "Detach surviving content as-is", ("M11",)),
        Fixture("F-LIFECYCLE-FAILURE", "Lifecycle failure and retry", ("M11",)),
        Fixture("F-OFFLINE", "Unavailable source and assets", ("M9", "M12")),
        Fixture("F-NESTED-STRESS", "Nested instance plus shear plus appearance variation", ("M10",)),
        Fixture("F-TEXTURE-IN-PLACE", "Texture edited in place", ("M13",)),
        Fixture("F-SAME-VALUES", "Same evaluated values at a different time (Phase 2)", ("M12", "M13")),
        Fixture("F-UNDO-AFTER-DAMAGE", "Undo after partial external display damage", ("M11",)),
        Fixture("F-NO-OP-REFRESH", "No-op refresh", ("M12", "M14")),
    )
}
