"""Build the Proscenium extension zip for the current platform, with its runtime wheels.

    uv run python tools/build_extension.py [--source-dir DIR] [--output-dir DIR] [--check]

--check (build(..., sync=False)) skips steps 2 and 3's writes: the source dir is
only read, and the build fails if its wheels or generated block are out of date.

Steps:
1. Export the runtime dependencies (never the dev group) from uv.lock as a
   pylock and select each package's wheel for this machine. The uv environment
   runs Python 3.13 like Blender 5.2, so its tags match Blender's.
2. Sync <source>/wheels/ (generated, gitignored) to that set: a wheel already
   present with the locked sha256 is kept, missing ones are downloaded and
   hash-checked, stale ones are removed.
3. Rewrite the manifest's generated block (between BEGIN and END, above the
   first table) with the matching `wheels` key. `platforms` is not written: nothing is platform
   dependent yet. Add it once a platform-specific wheel is needed.
4. Validate and build with the extension CLI shipped in the bpy wheel, so no
   Blender binary is needed (docs/feasibility/runtime-record.md#packaging).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import tomllib
import urllib.request
from pathlib import Path

from packaging.pylock import PackageWheel, Pylock

from blender_paths import wheel_extension_cli

ROOT = Path(__file__).resolve().parents[1]
BEGIN = "# --- begin generated by tools/build_extension.py ---\n"
END = "# --- end generated ---\n"


def runtime_wheels() -> list[PackageWheel]:
    """This machine's wheel for every runtime package locked in uv.lock."""
    out = subprocess.run(
        ["uv", "export", "--locked", "--no-dev", "--no-emit-project", "--format", "pylock.toml"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    lock = tomllib.loads(out)
    lock.setdefault("packages", [])  # uv omits the key when there are no runtime dependencies
    wheels = []
    for package, dist in Pylock.from_dict(lock).select():
        if not isinstance(dist, PackageWheel):
            raise SystemExit(f"{package.name}: uv.lock has no wheel for this platform")
        wheels.append(dist)
    return sorted(wheels, key=lambda w: w.filename)


def sync_wheels(wheels: list[PackageWheel], dest: Path, *, write: bool = True) -> list[Path]:
    """Make dest hold exactly these wheels, downloading only missing or mismatched ones.

    With write=False nothing is changed: it fails unless dest already matches.
    """
    wanted = {w.filename: w.hashes["sha256"] for w in wheels}
    stale = [p for p in dest.glob("*.whl") if wanted.get(p.name) != hashlib.sha256(p.read_bytes()).hexdigest()]
    missing = [w for w in wheels if not (dest / w.filename).exists() or dest / w.filename in stale]
    if not write:
        if stale or missing:
            names = sorted({p.name for p in stale} | {w.filename for w in missing})
            raise SystemExit(f"{dest}: wheels differ from uv.lock ({names}); run tools/build_extension.py")
        return [dest / w.filename for w in wheels]
    for path in stale:
        path.unlink()
    for wheel in missing:
        path = dest / wheel.filename
        dest.mkdir(exist_ok=True)
        if wheel.url is None:
            raise SystemExit(f"{wheel.filename}: no download URL in uv.lock")
        with urllib.request.urlopen(wheel.url) as response:
            data = response.read()
        if hashlib.sha256(data).hexdigest() != wheel.hashes["sha256"]:
            raise SystemExit(f"{wheel.filename}: sha256 does not match uv.lock")
        path.write_bytes(data)
    return [dest / w.filename for w in wheels]


def sync_manifest(manifest: Path, wheels: list[Path], *, write: bool = True) -> bool:
    """Rewrite the generated block; returns whether the file changed.

    With write=False nothing is changed: it fails unless the block is already current.
    """
    text = manifest.read_text(encoding="utf-8")
    head, begin, rest = text.partition(BEGIN)
    _, end, tail = rest.partition(END)
    if not (begin and end):
        raise SystemExit(f"{manifest}: missing the generated-block markers {BEGIN.strip()!r} / {END.strip()!r}")
    hand_written = tomllib.loads(head + tail)
    if "wheels" in hand_written:
        raise SystemExit(f"{manifest}: 'wheels' is generated; remove it outside the markers")

    block = ""
    if wheels:
        # json.dumps of a list of plain strings is a valid TOML array.
        block = f"wheels = {json.dumps([f'./wheels/{w.name}' for w in wheels])}\n"
    new = head + BEGIN + block + END + tail
    if tomllib.loads(new).get("wheels", []) != [f"./wheels/{w.name}" for w in wheels]:
        raise SystemExit(f"{manifest}: the generated block must be above the first table")
    if new != text:
        if not write:
            raise SystemExit(
                f"{manifest}: the generated block is out of date with uv.lock; run tools/build_extension.py"
            )
        manifest.write_text(new, encoding="utf-8")
    return new != text


def _cli(*args: str) -> None:
    cli = wheel_extension_cli()
    if cli is None:
        raise SystemExit("bpy wheel not found: run from the uv environment (uv sync)")
    proc = subprocess.run([sys.executable, str(cli), *args], capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        raise SystemExit(f"extension {args[0]} failed ({proc.returncode}):\n{proc.stdout}{proc.stderr}")


def build(source_dir: Path, output_dir: Path, *, sync: bool = True) -> Path:
    """Sync wheels into the manifest, validate, and build; returns the archive path.

    With sync=False the source dir is only read: the build fails unless its wheels
    and generated block already match uv.lock. Safe to run concurrently (tests).
    """
    wheels = sync_wheels(runtime_wheels(), source_dir / "wheels", write=sync)
    if sync_manifest(source_dir / "blender_manifest.toml", wheels, write=sync):
        print("updated blender_manifest.toml wheels from uv.lock")
    manifest = tomllib.loads((source_dir / "blender_manifest.toml").read_text(encoding="utf-8"))
    archive = output_dir / f"{manifest['id']}-{manifest['version']}.zip"

    _cli("validate", str(source_dir))
    output_dir.mkdir(parents=True, exist_ok=True)  # the CLI does not create it
    archive.unlink(missing_ok=True)
    _cli("build", "--source-dir", str(source_dir), "--output-dir", str(output_dir))
    _cli("validate", str(archive))
    return archive


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--source-dir", type=Path, default=ROOT / "src" / "proscenium")
    parser.add_argument("--output-dir", type=Path, default=ROOT / "dist")
    parser.add_argument(
        "--check",
        action="store_true",
        help="never write to the source dir; fail if its wheels or manifest are out of date with uv.lock",
    )
    args = parser.parse_args()
    print(f"built {build(args.source_dir, args.output_dir, sync=not args.check)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
